### ISSUE TITLE
Missing from @extends

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#20]
In extended options, existing properties are not overwritten.

For example, the default of `plotOptions.scatter.findNearestPointBy` should be `xy`, but the API says `x`.

Another example, `plotOptions.column.cropThreshold` should be 50 by default, and `marker` should be removed.

Properties that don't exist on the parent object are correctly handled.

**Comment by cvasseng** [comment]
It looks like, in the case of `findNearestPoint`, the issue is that it _does_ overwrite the existing property (existing is set to default `xy`, but it's overwritten by `plotOptions.line.findNearestPointBy`). 

Are there any cases where there are properties that _should_ be overwritten if they exist? (this is what happens with everything now; the extend source gets full precedence over existing properties) 

If we need to support both, I think that we need to add more exclude tags, and let that dictate whether or not the source overwrites or not.

**Comment by TorsteinHonsi** [comment]
I would expect that any properties defined in the scatter overwrite those defined in line. In this case, scatter should default to `xy`, which it doesn't...

```js
/**
 * @extends {plotOptions.line}
 * @optionparent plotOptions.scatter
 */
seriesType('scatter', 'line', {

	/**
	 * The width of the line connecting the data points.
	 * 
	 * @type {Number}
	 * @sample {highcharts} highcharts/plotoptions/scatter-linewidth-none/ 0 by default
	 * @sample {highcharts} highcharts/plotoptions/scatter-linewidth-1/ 1px
	 * @default 0
	 * @product highcharts highstock
	 */
	lineWidth: 0,

	/**
	 */
	findNearestPointBy: 'xy',
```

![skjermbilde 2017-06-26 kl 10 13 58](https://user-images.githubusercontent.com/227836/27530275-3a377fbe-5a58-11e7-992e-d795010ce1c7.png)
